(function(){var h,aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},k;if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var l;a:{var ba={S:!0},ca={};try{ca.__proto__=ba;l=ca.S;break a}catch(a){}l=!1}k=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var da=k,m=function(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(da)da(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.W=b.prototype},n="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},p="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:
this,q=function(a,b){if(b){var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&n(c,a,{configurable:!0,writable:!0,value:b})}},ea=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
q("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=ea(this,a,"startsWith");a+="";var e=b.length,f=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var g=0;g<f&&c<e;)if(b[c++]!=a[g++])return!1;return g>=f}});
var r=function(){r=function(){};p.Symbol||(p.Symbol=fa)},fa=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}(),u=function(){r();var a=p.Symbol.iterator;a||(a=p.Symbol.iterator=p.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&n(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ha(this)}});u=function(){}},ha=function(a){var b=0;return ia(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})},ia=function(a){u();a={next:a};a[p.Symbol.iterator]=
function(){return this};return a};q("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}});q("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==ea(this,a,"includes").indexOf(a,c||0)}});var v=function(a){u();var b=a[Symbol.iterator];return b?b.call(a):ha(a)},w=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
q("WeakMap",function(a){function b(a){w(a,d)||n(a,d,{value:{}})}function c(a){var c=Object[a];c&&(Object[a]=function(a){b(a);return c(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d.delete(b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch($a){return!1}}())return a;var d="$jscomp_hidden_"+Math.random().toString().substring(2);c("freeze");c("preventExtensions");c("seal");var e=0,f=function(a){this.a=
(e+=Math.random()+1).toString();if(a){r();u();a=v(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};f.prototype.set=function(a,c){b(a);if(!w(a,d))throw Error("WeakMap key fail: "+a);a[d][this.a]=c;return this};f.prototype.get=function(a){return w(a,d)?a[d][this.a]:void 0};f.prototype.has=function(a){return w(a,d)&&w(a[d],this.a)};f.prototype.delete=function(a){return w(a,d)&&w(a[d],this.a)?delete a[d][this.a]:!1};return f});
q("Map",function(a){if(function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a(v([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(ab){return!1}}())return a;r();u();var b=new WeakMap,c=function(a){this.g={};this.a=f();this.size=
0;if(a){a=v(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};c.prototype.set=function(a,b){var c=d(this,a);c.list||(c.list=this.g[c.id]=[]);c.b?c.b.value=b:(c.b={next:this.a,l:this.a.l,head:this.a,key:a,value:b},c.list.push(c.b),this.a.l.next=c.b,this.a.l=c.b,this.size++);return this};c.prototype.delete=function(a){a=d(this,a);return a.b&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.g[a.id],a.b.l.next=a.b.next,a.b.next.l=a.b.l,a.b.head=null,this.size--,!0):!1};c.prototype.clear=
function(){this.g={};this.a=this.a.l=f();this.size=0};c.prototype.has=function(a){return!!d(this,a).b};c.prototype.get=function(a){return(a=d(this,a).b)&&a.value};c.prototype.entries=function(){return e(this,function(a){return[a.key,a.value]})};c.prototype.keys=function(){return e(this,function(a){return a.key})};c.prototype.values=function(){return e(this,function(a){return a.value})};c.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};
c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(a,c){var d=c&&typeof c;"object"==d||"function"==d?b.has(c)?d=b.get(c):(d=""+ ++g,b.set(c,d)):d="p_"+c;var e=a.g[d];if(e&&w(a.g,d))for(a=0;a<e.length;a++){var f=e[a];if(c!==c&&f.key!==f.key||c===f.key)return{id:d,list:e,index:a,b:f}}return{id:d,list:e,index:-1,b:void 0}},e=function(a,b){var c=a.a;return ia(function(){if(c){for(;c.head!=a.a;)c=c.l;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},
f=function(){var a={};return a.l=a.next=a.head=a},g=0;return c});
q("Set",function(a){if(function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a(v([b]));if(!d.has(b)||1!=d.size||d.add(b)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=b||f.value[1]!=b)return!1;f=e.next();return f.done||f.value[0]==b||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;r();u();var b=function(a){this.a=new Map;if(a){a=v(a);for(var b;!(b=
a.next()).done;)this.add(b.value)}this.size=this.a.size};b.prototype.add=function(a){this.a.set(a,a);this.size=this.a.size;return this};b.prototype.delete=function(a){a=this.a.delete(a);this.size=this.a.size;return a};b.prototype.clear=function(){this.a.clear();this.size=0};b.prototype.has=function(a){return this.a.has(a)};b.prototype.entries=function(){return this.a.entries()};b.prototype.values=function(){return this.a.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=b.prototype.values;
b.prototype.forEach=function(a,b){var c=this;this.a.forEach(function(d){return a.call(b,d,d,c)})};return b});q("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});q("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});
var ja=this,x=function(a){return"string"==typeof a},y=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},z=function(a,b){function c(){}c.prototype=b.prototype;a.W=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ca=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var A=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,A);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};z(A,Error);A.prototype.name="CustomError";var ka;var B=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");A.call(this,c+a[d])};z(B,A);B.prototype.name="AssertionError";
var la=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new B(""+e,f||[]);},C=function(a,b,c){a||la("",null,b,Array.prototype.slice.call(arguments,2));return a},D=function(a,b){throw new B("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},ma=function(a,b,c){x(a)||la("Expected string but got %s: %s.",[y(a),a],b,Array.prototype.slice.call(arguments,2));return a};var E=function(a){if(!na.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(oa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(pa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(qa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ra,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(sa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(ta,"&#0;"));return a},oa=/&/g,pa=/</g,qa=/>/g,ra=/"/g,sa=/'/g,ta=/\x00/g,na=/[\x00&<>"']/;var F=function(){this.a="";this.i=ua;this.g=null};F.prototype.toString=function(){return"SafeHtml{"+this.a+"}"};var ua={},G=function(a){var b=new F;b.a=a;b.g=0};G("<!DOCTYPE html>");G("");G("<br>");var va=function(){this.a=ja.document||document};var H={da:!0},wa={ea:!0},I=function(){throw Error("Do not instantiate directly");};I.prototype.H=null;I.prototype.toString=function(){return this.w};var J=function(){I.call(this)};z(J,I);J.prototype.D=H;var K=function(a,b){C(a,"Soy template may not be null.");b=a(b||xa,void 0,void 0);a=(ka||(ka=new va)).a.createElement("DIV");b=ya(b);var c=b.match(za);C(!c,"This template starts with a %s, which cannot be a child of a <div>, as required by soy internals. Consider using goog.soy.renderElement instead.\nTemplate output: %s",c&&c[0],b);a.innerHTML=b;1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a},ya=function(a){var b=typeof a;if(("object"!=b||null==a)&&"function"!=b)return String(a);
if(a instanceof I){if(a.D===H)return ma(a.w);if(a.D===wa)return E(a.w)}D("Soy template output is unsafe for use as HTML: "+a);return"zSoyz"},za=/^<(body|caption|col|colgroup|head|html|tr|td|th|tbody|thead|tfoot)>/i,xa={};var Aa=function(a){if(null!=a)switch(a.H){case 1:return 1;case -1:return-1;case 0:return 0}return null},M=function(a){if(null!=a&&a.D===H)return C(a.constructor===J),a;if(a instanceof F){var b=L;if(a instanceof F&&a.constructor===F&&a.i===ua)var c=a.a;else D("expected object of type SafeHtml, got '"+a+"' of type "+y(a)),c="type_error:SafeHtml";a=b(c,a.g)}else a=L(E(String(String(a))),Aa(a));return a},L=function(a){function b(a){this.w=a}b.prototype=a.prototype;return function(a,d){a=new b(String(a));
void 0!==d&&(a.H=d);return a}}(J);(function(a){function b(a){this.w=a}b.prototype=a.prototype;return function(a,d){a=String(a);if(!a)return"";a=new b(a);void 0!==d&&(a.H=d);return a}})(J);
var Fa=function(a){return null!=a&&a.D===H?(C(a.constructor===J),String(String(a.w).replace(Ba,"").replace(Ca,"&lt;")).replace(Da,Ea)):E(String(a))},N=function(a,b,c,d){a||D("expected param "+b+" of type "+d+(", but got "+(c instanceof Function?c.displayName||c.name||"unknown type name":c instanceof Object?c.constructor.displayName||c.constructor.name||Object.prototype.toString.call(c):null===c?"null":typeof c))+".");return c},Ga={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;",
"\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"},Ea=function(a){return Ga[a]},Da=/[\x00\x22\x27\x3c\x3e]/g,Ba=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,Ca=/</g;var Ha=function(a){var b=N(x(a.j)||a.j instanceof I,"columnName",a.j,"!goog.soy.data.SanitizedContent|string");a=N(x(a.inputType)||a.inputType instanceof I,"inputType",a.inputType,"!goog.soy.data.SanitizedContent|string");a='<input type="'+Fa(a)+'" name="from"/>'+(" to "+('<input type="'+Fa(a)+'" name="to"/>'));b=M(b)+":";return L(""+('<div class="column-filter"><label>'+b+"</label>"+a+"</div>"))};Ha.a="colab.components.interactiveTableTemplate.rangeFilter";
var Ia=function(a){a=N(x(a.j)||a.j instanceof I,"columnName",a.j,"!goog.soy.data.SanitizedContent|string");a=M(a)+":";return L(""+('<div class="column-filter"><label>'+a+'</label><input type="text"/></div>'))};Ia.a="colab.components.interactiveTableTemplate.queryFilter";
var Ja=function(a){var b=N(x(a.j)||a.j instanceof I,"columnName",a.j,"!goog.soy.data.SanitizedContent|string");a=N("array"==y(a.options),"options",a.options,"!Array<!goog.soy.data.SanitizedContent|string>");var c="";b=M(b)+":";c+='<div class="column-filter"><label>'+b+"</label><select><option></option>";b=a.length;for(var d=0;d<b;d++)c+="<option>"+M(a[d])+"</option>";return L(c+"</select></div>")};Ja.a="colab.components.interactiveTableTemplate.selectFilter";var O=function(){return L('<div class="interactive-table-header"><span class="display-count"></span> <button class="controls-show">Filter</button> </div><div class="collapsible-controls"></div><div class="interactive-table-gviz-container"></div>')};
O.a="colab.components.interactiveTableTemplate.table";var Ka=function(){return L('<div class="close">\u00d7</div><div class="column-filters-container"></div><div class="column-filter"><label>Search by all fields:</label><input type="text" class="table-filter-all-fields"></div>')};Ka.a="colab.components.interactiveTableTemplate.collapsibleControls";
var La=function(){var a=L("<select><option>10</option><option>25</option><option>50</option><option>100</option></select> ");return L(""+('<div class="num-per-page">Show '+(a+" per page")+"</div>"))};La.a="colab.components.interactiveTableTemplate.numPerPage";var P=function(a){return HTMLElement.apply(this,arguments)||this};m(P,HTMLElement);h=P.prototype;h.createdCallback=function(){this.B={allowHtml:!0,sort:"event",page:"enable",width:"100%"};this.c=new google.visualization.DataTable;this.u=[];this.I=[];C(O,"Soy template may not be null.");this.innerHTML=ya(O({},void 0,void 0));this.o=K(Ka,{});this.s=new google.visualization.Table(C(this.querySelector(".interactive-table-gviz-container")));this.N=this.querySelector(".display-count");this.J=K(La,{})};
h.attachedCallback=function(){var a=this;google.visualization.events.addListener(C(this.s),"page",function(b){Ma(a,b.page)});google.visualization.events.addListener(C(this.s),"sort",function(b){a.m=b.column;a.G=b.ascending;a.B.sortColumn=a.m;a.B.sortAscending=a.G;Q(a);R(a);a.dispatchEvent(new Event("selection-change"))});this.m=parseInt(this.getAttribute("sort-by-column"),10)||this.m;this.G="true"==this.getAttribute("sort-ascending");var b=this.J.querySelector("select"),c=parseInt(this.getAttribute("num-per-page"),
10);if(c){b.value=c;if(Number(b.value)!=c){var d=document.createElement("option");d.textContent=c;b.insertBefore(d,b.firstChild);b.value=c}this.A=Number(b.value)}b.addEventListener("change",function(){a.A=Number(b.value);R(a)});this.F=this.o.querySelector(".table-filter-all-fields");c=function(){Na(a)};this.F.addEventListener("keyup",c);this.F.addEventListener("blur",c);var e=this.querySelector(".controls-show");e.addEventListener("click",function(){a.querySelector(".collapsible-controls").appendChild(a.o);
e.disabled=!0});this.o.querySelector(".close").addEventListener("click",function(){a.o.remove();e.disabled=!1});this.o.addEventListener("filter-change",function(){Na(a);a.dispatchEvent(new Event("selection-change"))})};h.detachedCallback=function(){this.s&&google.visualization.events.removeAllListeners(this.s)};h.addRow=function(a,b){b=void 0===b?"":b;a=this.c.addRow(a);b&&this.c.setProperty(a,0,"className","id-"+b)};
h.addColumn=function(a,b,c){var d=void 0===c?{}:c,e=void 0===d.V?!1:d.V;c=void 0===d.sort?void 0:d.sort;d=this.c.addColumn(a,b,void 0===d.id?void 0:d.id);e||(e=null,"number"==a?e=new S(b,d):"boolean"==a?e=new Oa(b,d):"date"==a||"datetime"==a?e=new Pa(b,d):e=new Qa(b,d),this.o.querySelector(".column-filters-container").appendChild(e.a),this.u.push(e));c&&(this.I[d]=c)};
var Ma=function(a,b){var c=a.N;var d=a.h.getNumberOfRows();var e=a.c.getNumberOfRows(),f=e!=d;if(0==d)d=f?"No entries (filtered from "+(e+" total entries)"):"No entries";else if(1==d)d=f?"1 entry (filtered from "+(e+" total entries)"):"1 entry";else{b=1+b*a.A;var g=Math.min(d,b+a.A-1);d=f?b+(" to "+(g+(" of "+(d+(" entries (filtered from "+(e+" total entries)")))))):b+(" to "+(g+(" of "+(d+" entries"))))}c.textContent=d;(c=a.querySelector(".google-visualization-table-div-page"))&&c.insertBefore(a.J,
c.firstChild);a.dispatchEvent(new Event(T.M))},R=function(a){a.B.pageSize=a.A;a.s.draw(C(a.h),a.B);a.querySelector(".google-visualization-table").style.maxHeight="";a.querySelector(".google-visualization-table > div:first-child").style.maxHeight="";Ma(a,0)},Q=function(a){if(!(0>a.m||a.m>=a.c.getNumberOfColumns())){var b=a.h.getColumnType(a.m),c=a.h.getSortedRows([{column:a.m,desc:!a.G,compare:a.I[a.m]||function(a,c){"number"==b&&(a=isNaN(a)?-Infinity:a,c=isNaN(c)?-Infinity:c);return null==a?null==
c?0:-1:null==c?1:a>c?1:a<c?-1:0}}]),d=a.h.getViewRows();a.h.setRows(c.map(function(a){return d[a]}))}},Ra=function(a,b,c){if(0==b.length)return!0;if(1==b.length){for(var d=0;d<a.c.getNumberOfColumns();d++)if(a.c.getFormattedValue(c,d).toLowerCase().includes(b[0]))return!0;return!1}d=[];for(var e=0;e<a.c.getNumberOfColumns();e++)d.push(a.c.getFormattedValue(c,e));var f=d.join(" ").toLowerCase();return b.every(function(a){return f.includes(a)})},Na=function(a){var b=a.F.value,c=a.u.map(function(a){return a.g()});
b=b.trim().toLowerCase().split(" ");for(var d=[],e=new Set(a.h.getViewRows()),f=!1,g=0;g<a.c.getNumberOfRows();g++){var t=e.has(g);Ra(a,b,g)&&Sa(a,c,g)?(d.push(g),t||(f=!0)):t&&(f=!0)}f&&(a.h.setRows(d),Q(a),R(a))};P.prototype.getSelection=function(){return null!=this.h?this.h.getViewRows():null};var Sa=function(a,b,c){for(var d=0;d<a.u.length;d++){var e=b[d],f=a.c.getValue(c,a.u[d].U);if(!e(f))return!1}return!0};h=P.prototype;h.h=null;h.c=null;h.s=null;h.A=10;h.J=null;h.m=-1;h.G=!1;h.F=null;
h.o=null;h.N=null;h.u=null;h.I=null;h.B=null;var U=function(a,b){this.U=a;this.a=b},V=function(a,b){var c=function(){a.a.dispatchEvent(new Event("filter-change",{bubbles:!0}))};b.addEventListener("keyup",c);b.addEventListener("blur",c);b.addEventListener("change",c)},W=function(a,b,c){U.call(this,b,K(Ha,{j:a,inputType:c}));a=this.a;this.from=C(a.querySelector('input[name="from"]'));V(this,this.from);this.i=C(a.querySelector('input[name="to"]'));V(this,this.i)};m(W,U);
var S=function(a,b){W.call(this,a,b,"text")};m(S,W);S.prototype.g=function(){var a=parseFloat(this.from.value),b=parseFloat(this.i.value);return function(c){return Ta(a,b,Number(c))}};var Pa=function(a,b){W.call(this,a,b,"date")};m(Pa,W);Pa.prototype.g=function(){var a=Ua(this.from).getTime(),b=Ua(this.i),c=b.getDate();isNaN(c)||b.setDate(c+1);var d=b.getTime();return function(b){return Ta(a,d,b.getTime())}};
var Ua=function(a){a=new Date(a.value);var b=a.getTimezoneOffset();return isNaN(b)?a:new Date(a.getFullYear(),a.getMonth(),a.getDate(),a.getHours()+Math.floor(b/60),a.getMinutes()+b%60)},Qa=function(a,b){U.call(this,b,K(Ia,{j:a}));this.i=C(this.a.querySelector('input[type="text"]'));V(this,this.i)};m(Qa,U);Qa.prototype.g=function(){var a=this.i.value.trim().toLowerCase().split(" ");return function(b){return a.every(function(a){return String(b).toLowerCase().includes(a)})}};
var Oa=function(a,b){U.call(this,b,K(Ja,{j:a,options:["true","false"]}));this.i=C(this.a.querySelector("select"));V(this,this.i)};m(Oa,U);Oa.prototype.g=function(){if(!this.i.value)return function(){return!0};var a="true"==this.i.value;return function(b){return b==a}};function Ta(a,b,c){return isNaN(c)?!0:(isNaN(a)||c>=a)&&(isNaN(b)||c<=b)}var T=document.registerElement("colab-interactive-table",P);T.C={X:"boolean",K:"number",L:"string",Y:"date",Z:"datetime"};
T.O={P:"num-per-page",ba:"sort-by-column",aa:"sort-ascending"};T.R="selection-change";T.M="update-page";function Va(a,b){for(var c=T.C.K,d=void 0,e=0;e<a.length;e++){var f=null!=a[e][b].v?a[e][b].v:a[e][b],g=Number(f);if("string"==typeof f||g>=Number.MAX_SAFE_INTEGER||g<=Number.MIN_SAFE_INTEGER){c=T.C.L;break}}if(c==T.C.L){for(d=0;d<a.length;d++)null!=a[d][b].v?a[d][b].v=String(a[d][b].v):a[d][b]=String(a[d][b]);d=function(a,b){if(a.startsWith("-")&&!b.startsWith("-"))return-1;if(!a.startsWith("-")&&b.startsWith("-"))return 1;if(a.startsWith("-")&&b.startsWith("-")){var c=a;a=b;b=c}c=a.substr(0,a.indexOf("."))||
a;var d=b.substr(0,b.indexOf("."))||b;return c.length>d.length?1:c.length<d.length?-1:a>b?1:a<b?-1:0}}else for(e=0;e<a.length;e++)null==a[e][b].f&&(null==a[e][b]&&(a[e][b]=NaN),"number"==typeof a[e][b]&&(a[e][b]={v:a[e][b],f:String(a[e][b])}));return{type:c,T:d}}function Wa(a,b){for(var c=0;c<a.length;c++)a[c][b]=String(a[c][b])}
function Xa(a,b){if((a=a.querySelector("table"))&&!a.querySelector("colgroup")){var c=document.createElement("colgroup");b.forEach(function(a){var b=document.createElement("col");null!=a&&(b.style.width=a);c.appendChild(b)});a.insertBefore(c,a.firstChild)}}
var Ya=function(a){var b=a.elementId,c=a.data,d=new T;a.rowsPerPage&&d.setAttribute(T.O.P,a.rowsPerPage);for(var e=a.columns,f=0,g;g=e[f];f++){var t=g[0];t==T.C.K?(t=Va(c,f),d.addColumn(t.type,E(String(g[1])),{sort:t.T})):(Wa(c,f),d.addColumn(t,E(String(g[1]))))}for(e=0;e<c.length;e++)d.addRow(c[e],String(e));b&&(b=document.getElementById(b))&&b.appendChild(d);d.h||(C(d.c),d.h=new google.visualization.DataView(d.c));Q(d);R(d);a.columnWidths&&Xa(d,a.columnWidths);a.saveCallback&&d.addEventListener(T.R,
function(){var b=d.getSelection();null!=b&&a.saveCallback(b)});d.addEventListener(T.M,function(){resizeOutput();a.columnWidths&&Xa(d,a.columnWidths)});return d},X=["gvizInteractiveTable","create"],Y=ja;X[0]in Y||!Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());){var Za;if(Za=!X.length)Za=void 0!==Ya;Za?Y[Z]=Ya:Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}};}).call(this);
